### ISSUE TITLE
Server-to-Server communication using DOP. 

### ISSUE THREAD

**Issue by DaneTheory** [syncio/syncio-nodejs#11]
Around a year ago, DOP provided Server-to-Server communication. I'm noticing now, however, the documentation is rather explicit on Server-to-Browser based communication. Is the legacy functionality still supported?

Thanks!

**Comment by Josema** [comment]
This new version does not implement the concept of transports. So nodes must be connected manually. Here an example connecting Server and Browser using WebSockets:

```js
// Server
const { createNode } = require('dop')
const WebSocket = require('ws')
const wss = new WebSocket.Server({ port: 8080 })
const sum = (a, b) => a + b
const multiply = (a, b) => a * b
const getCalculator = () => ({ sum, multiply })
wss.on('connection', ws => {
    const client = createNode()
    client.open(ws.send.bind(ws), getCalculator)
    ws.on('message', client.message)
})
```

```html
// Browser
<script src="https://unpkg.com/dop"></script>
<script>
    const ws = new WebSocket('ws://localhost:8080')
    const server = dop.createNode()
    ws.onopen = async () => {
        const getCalculator = server.open(ws.send.bind(ws))
        const { sum, multiply } = await getCalculator()
        const result1 = await sum(5, 5)
        const result2 = await multiply(3, 3)
        alert(`${result1} ${result2}`) // 10, 9
    }
    ws.onmessage = e => server.message(e.data)
</script>
```
Hope this helps.

**Comment by DaneTheory** [comment]
Thanks for the quick reply @josema. Unfortunately the Server-to-Browser example you provided doesn’t work for Server-to-Server communication. Removing support for different Websocket transports isn’t necessarily the issue here. Even without it, there’s no reason one couldn’t swap out ws for uws manually (uws has been updated to primarily serve server side sockets). If I remember correctly, the legacy api for DOP was built atop ES6 proxy objects. The current api for DOP (if still working with proxy objects) is, if anything, far more improve than before. The difference I’m seeing is with how the new api has moved away from using observables along side mutations to provide the interconnects DOP instances a universal store by which to derive shared state. Ideally, DOP (for Server-to-Server) could act as a nice, lightweight solution for Service Discovery/Services Mesh and easier to implement way for managing IPC. Would you be against adding an additional library for DOP, like dop-node or dop-services, whatever; where, for example, essentially anyone can create an HTTP Server instance using whatever framework they’d like, then instantiate dop-node atop the server, binding the TCP socket to the ws socket (or Unix socket) via something like uws. Then in another Server instance, invoke dop-node and have it act as a slave to the master dop-node instance using ws+Unix:// or wss protocol. The first dop-node slave would then act as a message broker/bus. Any additional Servers Created that use dop-node would connect to the slave. The master instance would react to observable events in the slave (I.e. disconnects, hostname/port changes, etc.) The master instance could also provide rotatable public keys for individual sub-slave instances (like using jwts), while helping ahold of the private keys. The Message Bus/Broker (1st slave) would only emit changes it receives from the master or,inversely, any sub-slaves. With this approach, you could even go beyond Server-to-Server as daemonized instances running on one/many machines could utilize the same communication network without much retooling. I ask all this primarily because, currently, in order to accomplish all of this we typically need to utilize additional tools that quickly bloat any tech stack (Redis, Treaffick, Comsul, NGINx, RabbitMQ, DNS-SD, not to mention containerization, etc.) Nothing wrong with any of these, and for serious enterprise grade software architecture they are certainly the right fit. But for smaller apps or even prototypes, dop could relatively easily solve the basic needs the others do, minus all the time needed for setup/continued maintenance/etc.

**Comment by Josema** [comment]
> example you provided doesn’t work for Server-to-Server communication

Because that example is for Browser to Server. If you want to connect server to server this is an example of a client:
```js
// Client
const WebSocket = require('ws')
const ws = new WebSocket('ws://localhost:8080')
const server = createNode()
ws.on('open', async () => {
    const getCalculator = server.open(ws.send.bind(ws))
    const { sum, multiply } = await getCalculator()
    const result1 = await sum(5, 5)
    const result2 = await multiply(3, 3)
    console.log(result1, result2) // 10, 9
})
ws.on('message', server.message)
```
---

The decision of leaving ES6 Proxies is because it has several problems managing the state globally. If the state is stored globally you will have side effects that makes the code buggy. So in this new version patches and stores are created as pure functions therefore we can implement ES6 Proxies stores on top of that with a style similar to Immer.js. But is still in development:
https://github.com/DistributedObjectProtocol/dop/blob/produce/test/producePatch.js#L26

--- 

I'm a bit lost when you commented the approaches about slaves and masters using redis tcp...
