### ISSUE TITLE
Btc not credited to coinfy wallet

### ISSUE THREAD

**Issue by Websoli** [syncio/syncio-nodejs#13]
The coinfy repository has been archieved by  Josema the same creator for this App, i am not able to reply to your message because you have archieved the repository, i need help with the btc deposit which is still missing from the Coinfy wallet, i followed your instructions and exported the 12 keys to monedero wallet however there is still no funds in it. How do i go about getting my funds from my coinfy wallet, the blockchain have 121 confirmations for the transactions but my btc wallet still have no funds in it even after exporting the wallet to monedero.

**Comment by Josema** [comment]
I have unarchived the Coinfy project. Didn't know that archiving it would close all issues. Please, reopen this issue in [Coinfy issues](https://github.com/elevenyellow/coinfy/issues) and I will try to help you.
