### ISSUE TITLE
Issue on client with remote methods

### ISSUE THREAD

**Issue by zgsrc** [syncio/syncio-nodejs#3]
Awesome library.  Thanks for all your work!

I'm having an issue on the client having to do with the "path" variable being null/undefined when configuring remote methods.

Uncaught TypeError: Cannot read property '0' of undefined
    at Object.dop.core.configureObject (dop.js:2056)
    at Object.dop.core.configureObject (dop.js:2063)
    at Object.dop.register (dop.js:1044)
    at Object.dop.protocol._onsubscribe (dop.js:3386)
    at Object.dop.core.emitMessage (dop.js:1247)
    at WebSocket.onmessage (dop.js:259)

**Comment by Josema** [comment]
Hi there!

Would you provide a bit more of information? Any step to replicate the bug? How do you define the remote methods?

**Comment by zgsrc** [comment]
It was a function defined as a literal.  Like:

obj = { };
obj.a = () => console.log("hey")

It may have to do with me trying to compose (i.e. assign one to another) dop.register({ }) objects, which is clearly a no-no.

I am using dop with a class model, so having to go through dop.register is awkward, but I've rewritten the base classes to support "data injection" using ever more Proxy objects so that everything writes to one dop.register({ }).  However, I'm not seeing updates being pushed.  Seeing them with a refresh though.

Everything is working well for you?

**Comment by Josema** [comment]
You can assign a register object into another one but this will be converted into a new plain object.
```js
a = dop.register({})
b = dop.register({value:1234})
a.b = b
a.b === b //false
a.b.value === b.value //true
```

So if you now change `a.b.value = 2222` this won't affect `b.value` because are different objects.

- How do you observe mutations?
- Can I install your project and replicate the bug?

**Comment by zgsrc** [comment]
Right. Originally I was trying to have my class code operating on b.value
if you will, affect a.b.value. I get the proxy hierarchy has to be built
top down.

It’s trading software so a little hard to replicate but I will setup a test
case when I get home.

In terms of mutations I was able to get a model with no functions to
subscribe over websocket but I could see no further activity is taking
place over the socket after the initial sync. At the same time I can see
the dop model is changing on the server side through a repl session I have
open simultaneously.

Tried switching to socket.io before I left the house but have been unable
to connect. dop.name is undefined in my client btw, which messes up default
urls.

**Comment by Josema** [comment]
> Tried switching to socket.io before I left the house but have been unable
to connect. dop.name is undefined in my client btw, which messes up default
urls.

Wops! Just fixed that. Thank you.

Let me know when you can make the small setup to replicate the bug. I really would like to fix that bug.

**Comment by zgsrc** [comment]
Okay I got part of it.  Vue.js and DOP fight and break "set" operations on the client side, so even if the websocket is getting data, you stop seeing updates. 

 The other part (why I'm not seeing updates when I do my code injection) is probably a subtle bug on my side having to do with assignment yielding a static copy, as we discussed earlier.

**Comment by zgsrc** [comment]
I think I could fix this problem if there was a way to subscribe "onto" an existing object, similar to register.  That way, DOP isn't writing updates "under" another observer layer.

**Comment by zgsrc** [comment]
Also – while I'm asking for things ;) – if the library supported standard composition semantics i.e.:

a = dop.register({ }), b = dop.register({ });
a.b = b;
b.c = 10;
a.b.c == 10;

... and the register method accepted ES6 classes in addition to POJO's – whereby methods could be automatically re-bound (Function.bind) to the registered object, that would create a pretty intuitive programming model.  For example:

let a = new ClassModelElement();
let a_dop = dop.register(a);
  -> for (m in a) if (typeof m === "function") a[m] = a[m].bind(a_dop)

a.methodThatModifiesStateUsingThis();
// writes on "this" automatically get routed through a_dop, so DOP sees all

Obviously, you've thought about this problem a lot more than I have, so I really don't know what I'm talking about breaking.

**Comment by Josema** [comment]
> Okay I got part of it. Vue.js and DOP fight and break "set" operations on the client side, so even if the websocket is getting data, you stop seeing updates.

That's weird. I haven't test dop with vuejs yet. But I should if you really have problems working with both. Any idea of how to replicate that issue? With a minimum setup?

> The other part (why I'm not seeing updates when I do my code injection) is probably a subtle bug on my side having to do with assignment yielding a static copy, as we discussed earlier.

Do not assign a dop registered object into another. Well, you can but remember that is just a merge and will be different objects.

> I think I could fix this problem if there was a way to subscribe "onto" an existing object, similar to register. That way, DOP isn't writing updates "under" another observer layer.

This is my fault, I haven't documented this feature. But you can subscribe into a registered object.
```js
const obj = dop.register({})
await dopserver_instance.subscribe().into(obj) // this will just return obj, so no need to declare
```

> a = dop.register({ }), b = dop.register({ });
> a.b = b;

Try to avoid this if you can

> ... and the register method accepted ES6 classes in addition to POJO's – whereby methods could be automatically re-bound (Function.bind) to the registered object, that would create a pretty intuitive programming model

Yes, I agree that would be very helpful and intuitive. I took this way because didn't know the possible side effects, but probably this feature will be asked often so I will test tomorrow.
Having in mind that only the first level could be registered and deep classes will be ignored. Example:

```js
// This will work
const obj = dop.register(new MyClass())
```

```js
const obj = dop.register({
  hello: 'world',
  myclass: new MyClass() // inner properties or functions won't be observables
})
```

```js
const obj = dop.register(new MyClass()) // this works
obj.mysubclass = new MyClass() // inner properties or functions won't be observables
```

Would this work for you?

**Comment by zgsrc** [comment]
Got it! Thanks for all the detailed responses!

For the last part, I’m trying to understand why only the first layer would
be observed. Does that mean changes to deeper values would not be sent over
a transport? Don’t you have to wrap properties in Proxy all the way down?

**Comment by Josema** [comment]
Ok, imagine you have a class instantiated in a file
```js
// square.js
const square = new Rectangle(10, 10)
export default square
```

Now in your app you import that file
```js
import square from './square'
class App {
...
    this.square1 = square
...
    if (this.square1 === square) { ... }
...
}
```
All good here, but if you now decide to use dop and you wrap `App` as a registered object this line will fail `if (square === this.square1) { ... }` because `this.square1` is now a Proxy.

This problem would happen also with POJO objects but we don't know if users will need to have intact their class instances. So I think this approach will avoid too much side effects. And also if you need deep observability you can just change to POJO object. Is good to offer the two options rather than force one or another.

For now, I think is more save to treat instances as special values.
