### ISSUE TITLE
allow resubscribing to an object

### ISSUE THREAD

**Issue by VanCoding** [syncio/syncio-nodejs#4]
Hi and thanks for this awesome library!! :)
I'm doing my home automation with it and it works pretty well so far.

But I encountered a situation where I'd like to periodically unsubscribe and resubscribe to an object, and it does not seem to work currently. It throws the following error when doing it: `TypeError: dop.data.object[node.owner[object_owner_id]] is undefined`

example client
```
var dop = require("dop");
var client = dop.connect({url:'ws://'+location.hostname+':4444'});
client.on("connect",async ()=>{
	var x = await client.subscribe("x");
	await client.unsubscribe(x);
	x = await client.subscribe("x");
})
```

example server
```
var dop = require("dop");
var x = dop.register({});
dop.onSubscribe(name=>x);
dop.listen();
```

What's interesting though, is that I don't get the error when always creating a new object, like so:
```
var dop = require("dop");
dop.onSubscribe(name=>dop.register({}));
dop.listen();
```
Does `unsubscribe` destroy the object on the server or something?

**Comment by Josema** [comment]
Hi! Thanks for using dop :)

I forgot to delete the object reference in the client side when unsubscribing.
https://github.com/DistributedObjectProtocol/dop/commit/b520c5b2bfba8e897e09ee90c76c12f8a291e3e6#diff-2fd8eaa50890c3712d0f04d0499ee756

Just update to the new version (0.27.0) and the problem will gone.

Keep in mind that when getting the second object in client the object is a new object:
```js
var dop = require("dop")
var client = dop.connect({ url:'ws://'+location.hostname+':4444' })
var a = await client.subscribe()
await client.unsubscribe(a)
var b = await client.subscribe()
a === b // false
```

Also notice that you don't need to use `client.on("connect",async ()=>{` for this case. Let me know if something is wrong.

**Comment by VanCoding** [comment]
Wow, this was fast! Thanks a lot :)

Yes, I know the objects won't be the same, but that does not matter as the references to the old ones get destroyed and new references get created upon resubscribing.

Thanks for the tip with the "connect" event, I didn't know that. Does this mean, that subscribe will always try to reconnect if the client is currently disconnected, or does it just wait until its connected again before resolving?

**Comment by VanCoding** [comment]
In case you're interested what I'm doing in my home, keep reading, if not, just ignore this comment ;)

I've built one or multiple touchscreens into the walls of all rooms of my house, which display buttons or other control elements to toggle the lights, the blinds, see the temperature, starting / stopping music, controlling the volume etc. Every tablet can control everything in the house, but by default it only shows the controls for the room it's installed in, but you can also navigate to what any other tablet is showing.

And this is where subscribing/unsubscribing comes in: Every device in my house is represented by a dop object, that the tablets can subscribe to. But the tablets only subscribe to devices that they do show controls for on the screen. If you show another control page, the devices shown on the previous page automatically get unsubscribed and only get subscribed again when navigating back to that page.

This way, every tablet only subscribes to the devices it needs/cares for and does not get updates of the whole building. This saves a lot of bandwidth.

dop really fits this use case pretty well and I'm glad you invested the time realize it. Thank you very much for this! :)

**Comment by Josema** [comment]
subscribe() waits until there is a connection established. Keep in mind that you have to manage the connections and recconnections manually:
https://distributedobjectprotocol.org/api/javascript/Node-reconnect

--- 

Wow, that app sounds very interesting. Happy that dop works well for you. Just for to know, what kind of domotic are you using that allows you to code in JavaScript?

And also how did you discover dop?

**Comment by VanCoding** [comment]
I don't use any established smart home system. Since I'm a programmer and it's my own house, I like to do it my own way and create something unique. I just use a raspberry PI as central server, to which all devices are connected in some way (sometimes directly over LAN (relays), sometimes over WIFI (LIFX bulbs), sometimes over a bridge to some protocol.

I discovered dop after a long search through the NPM registry :)
