### ISSUE TITLE
Mutations for connected client(s) are slow with more dop registered objects(>=2000)!!

### ISSUE THREAD

**Issue by satyam10zs** [syncio/syncio-nodejs#5]
Hi,

DOP library is written very well. I am using it in one of my projects. 
Could you please suggest/answer my queries below.

My Scenario:
---------------
Lets say DOP server has 2000 objects registered and 5-10 DOP clients have subscribed to those 2000 objects to receive mutations.
The 2000 objects are updated every 500 milliseconds or below. With this configuration memory keeps increasing like more than 700MB+... so on and dop server goes down due to more memory consumption.

<--- Last few GCs --->

[7664:004209B0] 106816266 ms: Mark-sweep 680.7 (712.2) -> 680.7 (712.2) MB, 1905
.6 / 0.0 ms  allocation failure GC in old space requested
[7664:004209B0] 106818103 ms: Mark-sweep 680.7 (712.2) -> 680.7 (710.2) MB, 1837
.1 / 0.0 ms  last resort GC in old space requested
[7664:004209B0] 106819978 ms: Mark-sweep 680.7 (710.2) -> 680.7 (710.2) MB, 1875
.3 / 0.0 ms  last resort GC in old space requested

I modified following sections of library to achieve the result.
1. dop.core.sendMessages : here itself i called  dop.protocol._onpatch(node, request_id, node.requests[request_id], response); and commented the timer part to avoid resending of data via new createrequest.
2. Fixed the maximum limit for requests for every connected node. This  will not send every mutation to connected client.
dop.core.emitNodes = function (patch) {
for..
for..
if(Object.keys(node.requests).length > 10000) continue;     
3.ws.js
 function send(message) {
 if (socket.readyState === OPEN) {
 socket.send(message);
 } //no queue
}

Query??
--------
The mutations for connected client will be slow as long as new client keeps on connecting and subscribing the 2000 dop registered obejcts. Is there any way, i can increase the client limit with smooth and fast updates at their end without lag?. Now 10-15 client works ok with my approach mentioned above .

Regards,
Satyam Singh

**Comment by Josema** [comment]
Hi there, thank you for using dop :)

First of all I don't know if is a problem of memory, performance (cpu) or bandwith. Can you answer me some questions because is not clear for me where the bottle neck is. 

- Those 2000 dop objects could increase to the infinite? like 100k? or will always be like 2000?
- How large are the data of those objects? If those objects would be place in other node.js instance without dop, do you think the amount of memory used would be lower?
- The clients are connecting and disconnecting constantly?
- So if I do the math correctly: 2000 objects that mutates every 500ms and have to emit mutations to 10 clients: This is 2000*10 = 10000 mutations to emit every 500ms. Is this correct?

**Comment by satyam10zs** [comment]
System Configuration : 32-bit/i3 core processor, 4GB Ram /1 TB  HD

- Those 2000 dop objects could increase to the infinite? like 100k? or will always be like 2000?
  - Dop objects could increase to a limit but the limit will be fixed maximum 10000-20000.
- How large are the data of those objects? If those objects would be place in other node.js instance without dop, do you think the amount of memory used would be lower?
  - as of now, every dop object contains a data member having a float value. 
  - Memory usage could be lower. But my point is if no. of registered dop object is more like 2000 and every data member of the dop object(s) is getting updated very very frequently using some other data source/ callback, or any other way, for every connected client which has subscribed to 2000 dop objects, dop maintains a requests {} object which will keep on filling and that is the main cause of memory increasing, also it waits for the ack from connected client to remove the request id which makes the situation worse for more no of clients. If i dont wait for ack and no timer for request to go in createrequest mode, and having limit set  to request {} object the problem of memory is solved. But still  sendMessage and frequent updates for dop objects in parallel don't always let the request {} objects to get cleared smoothly. I mean to say there still exists some lag between request {} object filled and sendMessage to send data to client.
- The clients are connecting and disconnecting constantly?
  - Right now i am testing with 10 clients (each subscribed to 2000 dop objects). I have not tested for client connection/disconnection part constantly. For my test case, i simply connect 10 clients and observe for mutations without any disconnect.
- So if I do the math correct: 2000 objects that mutates every 500ms and have to emit mutations to 10 clients: This is 2000*20 = 10000 mutations to emit every 500ms. Is this correct?
  - 20000 mutations to emit every 500ms (_2000 mutations for 10 clients_)

**Comment by Josema** [comment]
I just did a small refactor of your code reusing the `for` that we already had on top:
https://github.com/DistributedObjectProtocol/dop/commit/ccf3a7ce5135ec4332b6273e38850695f11afd05#diff-780f886728a9a5da7d7c515ae23710bf

**Comment by satyam10zs** [comment]
Ok. Could you please suggest solution(s) for my query  https://github.com/DistributedObjectProtocol/dop/issues/5#issuecomment-416282282

**Comment by Josema** [comment]
To be honest I don't have a quick solution for that, unless I replicate the problem somehow. I can try to create a scenario with the specification defined above and make a lot of tests, but that takes time.

Is it possible to use your code? Or a lite version to simulate the scenario you are mentioning?

**Comment by Josema** [comment]
Hi, could you explain a bit better this:

> If i dont wait for ack and no timer for request to go in createrequest mode, and having limit set to request {} object the problem of memory is solved. 

Ack is act? I always use Grammarly or google translate to make sure that the text is almost correct.

**Comment by satyam10zs** [comment]
https://github.com/DistributedObjectProtocol/dop/issues/5#issuecomment-416532397
I cannot provide you with my code due to official reasons. I will try to create a sample code as soon as possible. 

https://github.com/DistributedObjectProtocol/dop/issues/5#issuecomment-416851358
As per current implementation of dop, for any connected client node, any pending request will only get removed from memory when the connected client node sends a response. For example for request id 22, the response is -22 ..... This is completely ok. But what if there are many clients and many registered dop objects and too many frequent updates as I mentioned earlier, this may create a lag to wait for the response. 
Avoiding response may reduce the processing cycle of node js app. 

Also if the request packet does not get transferred to the client, it exists and on timeout, the request is deleted and recreated. I am just avoiding this due to too many frequent updates.



 dop.core.sendMessages = function (node) {
        ...
                    message.timeout = setTimeout(function () {
                         if (node.requests[request_id] !== undefined) {
                        dop.protocol['on' + nameinstruction + 'timeout'](node, request_id, message);
                        delete node.requests[request_id];
                        // }
                    }, dop.protocol.timeouts[nameinstruction]);
          .....
            }

**Comment by Josema** [comment]
> But what if there are many clients and many registered dop objects and too many frequent updates as I mentioned earlier, this may create a lag to wait for the response.

Let's put an example here to clarify:
1. One mutation is received in one of the objects of the server.
2. Server sends the mutation (patch) to the 10 clients you have connected
3. For this task server have created 10 requests objects internally to manage the response (state)
4. Only 8 clients receive this patch, the other 2 left had an error in the browser (for example)  and can't send the response.
5. Server receive 8 responses, and the 2 left are pending with a timeout of https://github.com/DistributedObjectProtocol/dop/blob/02bb08f1f2bfa12427f9bb18f0ccd41a199d1f8d/src/protocol/timeouts.js#L7
6. After one second (1000ms) this two request objects created before will be deleted

Does this make sense? I don't see the problem of this workflow here. Maybe I'm missing something that you figure out... Explain me what is wrong in this process.

**Comment by Josema** [comment]
@satyam10zs shall I close this?

**Comment by satyam10zs** [comment]
As of now OK.
