### ISSUE TITLE
example for connecting with nodejs http server

### ISSUE THREAD

**Issue by hlb-schmidt** [syncio/syncio-nodejs#7]
is there a simple example for https://distributedobjectprotocol.org/guide/javascript/connecting-nodes with nodejs http server and web-browser?

i tried this:

```
const Fs = require("fs");
const Dop = require("dop");
const Http = require("http");

const httpd = Http.createServer((request, response)=>{
	switch (request.url) {
		case "/":
			response.writeHead(200, {"Content-Type":"text/html"});
			response.end(`
				<html>
				<head>
					<script src="/dop.js"></script>
					<script>
						const server = dop.connect();
						server.on("connect", ()=>{
							console.log("connected");
						});
					</script>
				</head>
				<body><h1>hello world</h1></body>
				</html>
			`);
			break;
		case "/dop.js":
			response.writeHead(200, {"Content-Type":"application/javascript"});
			Fs.createReadStream("./node_modules/dop/dist/dop.js").pipe(response);
			break;
		default:
			response.writeHead(404, {"Content-Type":"text/plain"});
			response.end("not found.");
			break;
	}
});

const dopd = Dop.listen({httpServer:httpd});
dopd.on("connect", (node)=>{
	console.log("connected");
});

httpd.listen(8000, "localhost");
```

and i only get "connected" printed in web-browser devtools console (chromium 69.0.3497.81), but not in nodejs (10.10.0) console.

what am i doing wrong?

ps. i could not find in dop documentation how to do web socket upgrades (or even what options does `.listen()` use), but found `.listen({httpServer:httpd})` in some other example, in the hopes it does that...

**Comment by Josema** [comment]
Have a look the example of **Using httpServer**:
https://distributedobjectprotocol.org/transports/javascript/websockets

**Comment by hlb-schmidt** [comment]
ah, thank you, somehow i missed that link.

so the example i posted should work?
but why doesn't it print "connected" in nodejs?

**Comment by Josema** [comment]
I had a bug on the latest version, maybe could be that. Please make sure you are using the 0.30.2 version. Your example is working for me, it prints "connected" in nodejs and the browser.

Let me know if you have any other issue, and sorry about that.
